import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#F7F9FC',
        'background-alt': '#F0F4F8',
        'background-dark': '#071018',
        'background-dark-alt': '#0B1117',
        foreground: '#101820',
        'foreground-alt': '#5E6B78',
        'foreground-muted': '#5E6B78',
        'foreground-on-dark': '#F7F9FC',
        'foreground-on-dark-alt': '#DCE5ED',
        surface: '#FFFFFF',
        'surface-alt': '#F7F9FC',
        'surface-elevated': '#FFFFFF',
        'surface-dark': '#121C26',
        'surface-dark-alt': '#0B1117',
        border: '#DCE5ED',
        'border-alt': '#C4CDD5',
        'border-dark': '#1B2633',
        'border-dark-alt': '#0B1117',
        primary: '#1687E8',
        'primary-dark': '#0F5CB8',
        'primary-light': '#45B6FF',
        'primary-foreground': '#FFFFFF',
        secondary: '#121C26',
        'secondary-dark': '#0B1117',
        'secondary-light': '#5E6B78',
        'secondary-foreground': '#FFFFFF',
        accent: '#45B6FF',
        'accent-foreground': '#FFFFFF',
        muted: '#F0F4F8',
        'muted-foreground': '#5E6B78',
        success: '#10B981',
        'success-foreground': '#FFFFFF',
        warning: '#F59E0B',
        'warning-foreground': '#FFFFFF',
        error: '#EF4444',
        'error-foreground': '#FFFFFF',
        info: '#1687E8',
        'info-foreground': '#FFFFFF',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        mono: [
          'JetBrains Mono',
          'Menlo',
          'Monaco',
          'Consolas',
          'Liberation Mono',
          'Courier New',
          'monospace',
        ],
      },
      fontSize: {
        'display-large': 'clamp(3rem, 6vw, 5rem)',
        'display-medium': 'clamp(2.5rem, 5vw, 4rem)',
        'display-small': 'clamp(2rem, 4vw, 3rem)',
        h1: 'clamp(2.5rem, 5vw, 4rem)',
        h2: 'clamp(2rem, 4vw, 3rem)',
        h3: 'clamp(1.75rem, 3.5vw, 2.5rem)',
        h4: '1.5rem',
        h5: '1.25rem',
        h6: '1.125rem',
        'body-large': '1.125rem',
        'body-medium': '1rem',
        'body-small': '0.875rem',
        'label-medium': '0.875rem',
        'label-small': '0.75rem',
        caption: '0.75rem',
        overline: '0.6875rem',
      },
      lineHeight: {
        tight: '1.1',
        snug: '1.25',
        normal: '1.5',
        relaxed: '1.625',
        loose: '2',
      },
      letterSpacing: {
        tighter: '-0.05em',
        tight: '-0.025em',
        normal: '0',
        wide: '0.025em',
        wider: '0.05em',
        widest: '0.1em',
      },
      borderRadius: {
        small: '0.25rem',
        medium: '0.375rem',
        large: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
      },
      boxShadow: {
        small: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        medium: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        large: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
      },
      zIndex: {
        base: '0',
        content: '10',
        sticky: '20',
        header: '30',
        dropdown: '40',
        modal: '50',
        toast: '60',
        tooltip: '70',
      },
      maxWidth: {
        'container-standard': '1200px',
        'container-wide': '1400px',
        'container-narrow': '800px',
      },
      width: {
        'container-standard': '1200px',
        'container-wide': '1400px',
        'container-narrow': '800px',
      },
      screens: {
        'mobile-large': '430px',
        tablet: '768px',
        laptop: '1024px',
        desktop: '1280px',
        'desktop-large': '1440px',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '300ms',
        slow: '500ms',
      },
    },
  },
  plugins: [],
  corePlugins: {
    lineClamp: true,
  },
};
export default config;
